### ISSUE TITLE
When the token expired, the user still shows on the nav bar

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/navbar#13]
The token has expired then I was taken to the login page. However, the user still shows on the navbar and I can access 'change password' 
![capture](https://cloud.githubusercontent.com/assets/1034174/6697304/e9e499ec-ccac-11e4-9f5a-3eb6678ec143.PNG)

**Comment by stevenolen** [comment]
the rewrite of this tool catches expired tokens everywhere possible.  This case is definitely still possible in very particular instances, but there is very little else that the navbar can do save pinging the ohmage server constantly, which is a little overboard.
