### ISSUE TITLE
Clicking campaign on navbar from Response Manager page is not working

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/navbar#14]
I was on Response Manager page and was trying to go back to campaigns list. I clicked "Campaigns" on the navbar but nothing happened. I have to click Mobilize and then Campaigns on the navbar.

**Comment by stevenolen** [comment]
the navbar was getting confused since it was running inside itself :+1: 

This actually needed to be fixed in the campaign manager (which was causing the nav-in-nav). https://github.com/mobilizingcs/campaign_mgmt/commit/f08700f7c850b35004e52c28a89936087f33faad

**Comment by stevenolen** [comment]
OK nevermind. this is still happening :confounded:

**Comment by stevenolen** [comment]
@ctrance this one should be fixed...if you could test! :)

**Comment by ctrance** [comment]
fixed now!
