### ISSUE TITLE
Classes link in navbar shows incorrect list

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/navbar#15]
When I go to Admin>Users and check my account (mwf.cathy) it shows I have access to 7 classes but when I click "Classes" on the navbar, the list only shows 1 class.

**Comment by stevenolen** [comment]
this would actually be an issue for https://github.com/mobilizingcs/teacher, but I think it may be working as intended...

In the admin tool you are given access to any class an admin should see whereas in the "class setup" tool it is only classes you belong to (and then, even less as when it is run on a mobilizingcs.org domain it only displays classes where the urn matches the lausd format?)

**Comment by jeroenooms** [comment]
We should make it more clear that the 'class setup' tool was never intended as a general class manager. It only works for these very specific auto generated classes that follow the naming conventions and have uses that were generated only with /user/setup.

**Comment by ctrance** [comment]
It got me confused because when I go to ohmageX mobile app I have access to campaigns from more than 1 class and not just TPP Internal class.
